### ISSUE TITLE
Retrieval mechanisms for the active ModelInstanceRepository inhibit extension patterns.

### ISSUE THREAD

**Issue by peter-mcclonski** [TechnologyBrewery/fermenter#78]
Currently, the only mechanism to retrieve the configured `ModelInstanceRepository` implementation instance, and thus to interrogate the underlying schemas informing generation, is to use this static method provided in the `ModelInstanceRepositoryManager` class: 

```
    public static <V> V getMetamodelRepository(Class<V> type) {
        Map<String, Object> instanceMap = threadBoundInstance.get();
        return type.cast(instanceMap.get(type.toString()));
    }
```

Suppose a fermenter-based project `Project_A` provides their own `ModelInstanceRepository` implementation, `MIR_A`.  Within the project's generators, they may be forced to include code such as the following:

```
MIR_A metamodelRepository = ModelInstanceRepositoryManager
                .getMetamodelRepository(MIR_A.class);
```

This will work fine for this initial project.  However, if another project `Project_B` is created to extend `Project_A`, with its own `ModelInstanceRepository` implementation `MIR_B extends MIR_A`, then existing calls of the above snippet will fail with null pointer exceptions.  This is due to the naive string-name lookup method found in the `getMetamodelRepository` method above.  Extension patterns are thus inhibited.

**Comment by peter-mcclonski** [comment]
Q: There are multiple potential paths to resolution here.  We can either improve the behavior of the existing method of retrieval, or deem that method undesirable, and add an improved method of retrieving the `ModelInstanceRepository` instance.  The former has the advantage of not requiring changes to existing downstream code, while the latter is probably the overall 'better' approach in a vacuum.  

Feedback required from maintainers.

**Comment by peter-mcclonski** [comment]
@d-ryan-ashcraft It looks like support for multiple simultaneous Metamodel Repositories is an intended feature, even validated by test cases.  With that said, it's impossible to achieve from a plugin execution context, as the `metadataRepositoryImpl` config option only accepts a single value.  I'm reluctant to do anything that would kill off the existing capability, although I'm curious to understand more about the intended use case(s), as it introduces a lot of potential complexity.

My concern comes with respect to conflict resolution.  Let's say there exist three classes: `MIR_A implements ModelInstanceRepository`, `MIR_B extends MIR_A`, and `MIR_C extends MIR_A`.  For whatever reason, let's suppose we've added both `MIR_B` and `MIR_C` to the repository manager.  If I call `getMetamodelRepository(MIR_A.class)`, should I expect to get back `MIR_B`, `MIR_C`, both, or nothing?  If nothing, that retains the current problem.  If both, we need to change the method heading, constituting a breaking api change. If one of the two, we're breaking the tie arbitrarily, which feels wrong.

Maybe I'm hugely overthinking this.

**Comment by d-ryan-ashcraft** [comment]
I think you can only pass in one `ModelInstanceRepository` per execution.  So if you pass in `MIR_A`, you'll get `MIR_A`.  If you want `MIR_C` or `MIR_B`, you need to pass those in.  But if you want all three (or two of three), then you can run multiple exeuctions.

**Comment by peter-mcclonski** [comment]
> I think you can only pass in one `ModelInstanceRepository` per execution. So if you pass in `MIR_A`, you'll get `MIR_A`. If you want `MIR_C` or `MIR_B`, you need to pass those in. But if you want all three (or two of three), then you can run multiple exeuctions.

I want to make sure I understand this correctly.  Does this mean that if I've configured `MIR_B` in my plugin execution (it therefore exists in the map), and request `MIR_A`, it's reasonable to return `null` or otherwise not return anything, even though `MIR_B` is a valid specific classifier of `MIR_A`?

**Comment by d-ryan-ashcraft** [comment]
We probably should look at it more like you just ask the `GenerationContext` for the current `ModelInstanceRepository` rather than using the `ModelInstanceRepositoryManager`.  Using multiple executions seems a lot cleaner than trying to handle multiple simultaneously in one execution.

**Comment by carter-cundiff** [comment]
Additional functionality is needed for classes that need access to the current `ModelInstanceRepository` before the `GenerationContext` has been created. See #80 for more details.
